"""Add image_url to announcements

Revision ID: 03db12991ee1
Revises: 108db025b565
Create Date: 2025-08-02 01:06:57.119819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03db12991ee1'
down_revision: Union[str, Sequence[str], None] = '108db025b565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'image_url')
    # ### end Alembic commands ###
