"""Add region to announcements

Revision ID: 108db025b565
Revises: 3ddcd4b61551
Create Date: 2025-07-31 12:12:53.279477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108db025b565'
down_revision: Union[str, Sequence[str], None] = '3ddcd4b61551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('region', sa.String(), nullable=True))
    op.create_index(op.f('ix_announcements_region'), 'announcements', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_region'), table_name='announcements')
    op.drop_column('announcements', 'region')
    # ### end Alembic commands ###
